name: Code Style

on:
  - push
  - fork
  - pull_request

jobs:
  code-style:
    runs-on: ubuntu-latest
    name: 'Check code style for Node.js v${{ matrix.node-version }}'
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '19']
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node-version }}-
      - name: Install dependencies
        run: yarn install --dev
      - name: Run syntax linter
        run: yarn run cs
