name: Unit Test

on:
  - push
  - fork
  - pull_request

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: 'Running unit tests for Node.js v${{ matrix.node-version }}'
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '19']
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v3
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node-version }}-
      - name: Install dependencies
        run: yarn install --dev
      - name: Run unit tests
        run: yarn run test:unit
